# -*- coding: utf-8 -*-
"""Cyber threat dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sG2Txe7VrpnejQLARcwSwPMNnd9g0HpZ
"""

!pip install dash plotly pandas requests

!pip install pandas plotly dash dash-bootstrap-components

import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objects as go
import pandas as pd
import dash_bootstrap_components as dbc

df = pd.read_csv('//synthetic_cyber_threat_data.csv')

# Create Dash App
app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

# Layout
app.layout = html.Div([
    dbc.Row([
        dbc.Col(html.H1("Cyber Threat Dashboard", className="text-center"), width=12)
    ]),

    # Threat Level Pie Chart
    dbc.Row([
        dbc.Col(dcc.Graph(
            id='threat-level-pie',
            figure={
                'data': [
                    go.Pie(labels=df['Asset'], values=df['Threat Level'], hole=0.3)
                ],
                'layout': go.Layout(title='Threat Level per Asset')
            }
        ), width=6),

        # Vulnerabilities Bar Chart
        dbc.Col(dcc.Graph(
            id='vulnerabilities-bar',
            figure={
                'data': [
                    go.Bar(x=df['Asset'], y=df['Vulnerabilities'], name='Vulnerabilities', marker=dict(color='orange'))
                ],
                'layout': go.Layout(title='Vulnerabilities per Asset')
            }
        ), width=6),
    ]),

    # Alerts Table
    dbc.Row([
        dbc.Col(html.Div([
            html.H3('Alerts Table'),
            html.Table([
                html.Thead(html.Tr([html.Th("Asset"), html.Th("Alerts")])),
                html.Tbody([
                    html.Tr([html.Td(df['Asset'][i]), html.Td(df['Alerts'][i])]) for i in range(len(df))
                ])
            ])
        ]), width=12)
    ])
])

# Run the App
if __name__ == '__main__':
    app.run_server(debug=True)